### ISSUE TITLE
error.log does not contain timestamps

### ISSUE THREAD

**Issue by danstoner** [iDigBio/idigbio-media-appliance#8]
The error log contains tracebacks but no timestamps of when they occurred.

The debug file archive may contain activity from months or even years prior. The error log would be more useful if we could tell when the exception occurred (current issue or not).

**Comment by danstoner** [comment]
Example:

```
Error in readdir
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
    context)
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: media.path

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\idigbio_media_appliance\lib\workwork.py", line 210, in media_csv
    for m in query.all():
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\orm\query.py", line 2613, in all
    return list(self)
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\orm\query.py", line 2760, in __iter__
    self.session._autoflush()
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\orm\session.py", line 1303, in _autoflush
    util.raise_from_cause(e)
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\util\compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
    raise value
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\orm\session.py", line 1293, in _autoflush
    self.flush()
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\orm\session.py", line 2019, in flush
    self._flush(objects)
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\orm\session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
    raise value
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\orm\session.py", line 2101, in _flush
    flush_context.execute()
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 373, in execute
    rec.execute(self)
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 532, in execute
    uow
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\orm\persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\orm\persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\engine\base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\engine\base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context
    context)
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\util\compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\util\compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
    context)
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.IntegrityError) UNIQUE constraint failed: media.path [SQL: 'INSERT INTO media (media_type, mime, path, file_reference, props, image_hash, status, status_date, status_detail, appuser_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (None, None, 'Z:\\Complete_JPG\\To-be-Uploaded\\UT0042745.jpg', '85def5090403c843be6fb81a5faf8d55', '{}', None, None, None, None, 1)]
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\site-packages\idigbio_media_appliance\api\services.py", line 190, in check_readdir_task
    csv_file_name = read_worker.get()
  File "C:\Users\mbaker\AppData\Local\Continuum\idigbiomediaappliance\lib\multiprocessing\pool.py", line 608, in get
    raise self._value
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: media.path [SQL: 'INSERT INTO media (media_type, mime, path, file_reference, props, image_hash, status, status_date, status_detail, appuser_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (None, None, 'Z:\\Complete_JPG\\To-be-Uploaded\\UT0042745.jpg', '85def5090403c843be6fb81a5faf8d55', '{}', None, None, None, None, 1)]

```
The 'Error in readdir' exception is generated in ```/idigbio_media_appliance/api/services.py```

For some reason the file_handler logger that is created in ```app.py``` is not getting the format (FORMAT) applied to it.
